### ISSUE TITLE
Add a new Baudrate dropdown menu

### ISSUE THREAD

**Issue by coliss86** [MarginallyClever/Makelangelo-software#482]
**Is your feature request related to a problem? Please describe.**
I'm setting up a new HC06 bluetooth adapter which speed cannot get higher than 115200.
So I need to specify it but I don't where to put this settings.
The most evident place is next to the dropdown menu of port: 
![image](https://user-images.githubusercontent.com/23615562/151445327-3c38543f-a792-42e4-bbbf-d0f671b37289.png)

But it will break the `TCPConnection` which is not concerned by this settings.
Maybe a better place would be in the `PlotterSettingsPanel`
![image](https://user-images.githubusercontent.com/23615562/151445254-09344df5-d2c2-4f27-b711-7874849d7b03.png)

Where do you think is the best place ?

**Comment by i-make-robots** [comment]
No!  One baud rate to rule them all!

**Comment by i-make-robots** [comment]
Get a better bluetooth adapter :)

**Comment by coliss86** [comment]
So you don't want this parameter ?

**Comment by i-make-robots** [comment]
I don't.  I want when-apple-was-good simplicity.

**Comment by coliss86** [comment]
It is a common configuration for software that communicates with serial port. It is even available in pronterface, octoprint...
We can select by default `250000` and let the user select a different speed. Why not offering this possibility ?

**Comment by PPAC37** [comment]
For me also it seems more practical to have the choice of the baudrate modifiable by the user.

Unless you have to reserve it for a paid pro version or if it's to encourage people to get into java development so that they can change it themselves:) 

or possibly a command line argument when launching from a command line (if you don't want to have to add something to modify it in the graphical interface)

**Comment by i-make-robots** [comment]
Fine.  I would put the baud rate on the connect dialog.  The default should stay 250000.

**Comment by i-make-robots** [comment]
In the past I had connection dialog pop-ups because I wanted to be able to seamlessly switch to TCP/IP in case in future there was support for wifi in the robot.  nothing on the near side of TextInterfaceToNetworkSession (inside makelangelo.*) should know about what kind of connection is available.  nothing on the far side (inside communications.*) should know about the makelangelo app.  At least... that was the idea.

**Comment by coliss86** [comment]
Ok I see, I'll first create something that works and then refactor it to meet your goals
